# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuration commune à toutes les machines
  config.vm.box = "centos/7"
 

  # Config une première VM "node"
  config.vm.define "node" do |node|
    # remarquez l'utilisation de 'node.' défini sur la ligne au dessus
    node.vm.network "private_network", ip: "192.168.2.11"
    node.vm.hostname = "node.tp2.b2"

      node.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = node
      # Création d'un second disque de 5Go :
      v.customize ['createhd', '--filename', "/tmp/disk.vdi", '--size', 5 * 1024]
      v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", "/tmp/disk.vdi"]
      end

      # Installation de paquets lors du premier boot :
      config.vm.provision "shell", inline: "yum install vim || apt-get install vim"
      
    
  end

 
  ## Les 3 lignes suivantes permettent d'éviter certains bugs et/ou d'accélérer le déploiement. Gardez-les tout le temps sauf contre-indications.
  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false
  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false 
  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true
end





