# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vbguest.auto_update = true
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Config une première VM "node1"
  config.vm.define "node1" do |node1|
    # remarquez l'utilisation de 'node1.' défini sur la ligne au dessus
    node1.vm.network "private_network", ip: "192.168.56.11"
    # Define a hostname
    node1.vm.hostname = "node1.tp2.b2"
    # Define a static IP
    node1.vm.network "private_network", ip: "192.168.2.21/24"
    # Section specific to VirtualBox
    node1.vm.provider "virtualbox" do |v|
      # Define a specific amount of memory
      v.memory = 1024
    end
  end
end
